services:
  - name: docker:dind
    command: ["--tls=false"]

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_REPO: n1rvana/web-app
  IMAGE_TAG: '1.0'

stages:
  - compile_app
  - verify_app
  - build_image
  - deploy

compile_app:
  stage: compile_app
  image: maven:3.8.5-openjdk-17
  script:
    - mvn compile

run_tests:
  stage: verify_app
  image: maven:3.8.5-openjdk-17
  script:
    - mvn verify

build_image:
  stage: build_image
  image: docker:24.0.2-cli
  before_script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
  script:
    - docker build -t $DOCKER_REPO:$IMAGE_TAG . --no-cache
    - docker push $DOCKER_REPO:$IMAGE_TAG

deploy:
  stage: deploy
  before_script:
    - chmod 400 "$SSH_KEY"
  script:
    - scp -o StrictHostKeyChecking=no -i "$SSH_KEY" $CI_PROJECT_DIR/docker-compose.yml ec2-user@15.236.186.96:/home/ec2-user/docker-compose.yml
    - ssh -o StrictHostKeyChecking=no -i "$SSH_KEY" ec2-user@15.236.186.96 "docker ps -aq | xargs docker stop | xargs docker rm && docker images -aq | xargs docker rmi -f && docker-compose up -d"