INSERT INTO groups (group_name) VALUES ('JA-56');
INSERT INTO groups (group_name) VALUES ('ZU-43');
INSERT INTO groups (group_name) VALUES ('TT-78');
INSERT INTO groups (group_name) VALUES ('ZA-92');
INSERT INTO groups (group_name) VALUES ('BS-13');
INSERT INTO groups (group_name) VALUES ('DA-42');

INSERT INTO courses (course_name, course_description) VALUES ('History', 'the study of change over time');
INSERT INTO courses (course_name, course_description) VALUES ('Topography', 'the study of the land surface');
INSERT INTO courses (course_name, course_description) VALUES ('Chemistry', 'the science that deals with the properties, composition, and structure of substances');
INSERT INTO courses (course_name, course_description) VALUES ('Geography', 'the study of places and the relationships between people and their environments');
INSERT INTO courses (course_name, course_description) VALUES ('Astronomy', 'the study of everything in the universe beyond Earth''s atmosphere');
INSERT INTO courses (course_name, course_description) VALUES ('Physical_Education', 'the teaching and leading of physical activity');
INSERT INTO courses (course_name, course_description) VALUES ('Math', 'the science that deals with the logic of shape, quantity and arrangement');
INSERT INTO courses (course_name, course_description) VALUES ('Biology', 'a branch of science that deals with living organisms and their vital processes');
INSERT INTO courses (course_name, course_description) VALUES ('English_Language', 'introduction to english human language');
INSERT INTO courses (course_name, course_description) VALUES ('Physics', 'science that deals with the structure of matter');

INSERT INTO rooms (room_label, room_description) VALUES ('GEO', 'Geography room');
INSERT INTO rooms (room_label, room_description) VALUES ('MTH', 'Math room');
INSERT INTO rooms (room_label, room_description) VALUES ('HIS', 'History room');
INSERT INTO rooms (room_label, room_description) VALUES ('ENG', 'English room');
INSERT INTO rooms (room_label, room_description) VALUES ('BIO', 'Biology room');
INSERT INTO rooms (room_label, room_description) VALUES ('PHY', 'Physics room');

INSERT INTO role (role_name) VALUES ('admin'), ('student'), ('professor');

INSERT INTO lessons_time (lesson_time) VALUES ('8:00-9:30'), ('9:45-11:15'), ('11:30-13:00'), ('13:30-15:00'), ('15:15-16:45');

INSERT INTO users (user_name, user_lastname, role_id) VALUES ('admin', '', 1);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Victoria', 'Nazarova', 3);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Oksana', 'Boiko', 3);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Diana', 'Belova', 3);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Vitaliy', 'Rojkov', 3);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Artur', 'Morozov', 3);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Irina', 'Popova', 3);

INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Pavel', 'Ivanov', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Gleb', 'Burov', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Elena', 'Nosova', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Boris', 'Pahomov', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Maksim', 'Sidorov', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Alisa', 'Mironova', 2);

INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Nikolay', 'Ponomarev', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Inna', 'Lapina', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Roman', 'Smirnov', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Ivan', 'Lazarev', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Anna', 'Bezpalova', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Igor', 'Sokolov', 2);

INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Olga', 'Pavlova', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Marina', 'Tihonova', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Pavel', 'Bezpalov', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Ivan', 'Lazarev', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Igor', 'Pavlov', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Boris', 'Sokolov', 2);

INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Olga', 'Pahomova', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Marina', 'Lapina', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Pavel', 'Tihonov', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Ivan', 'Lazarev', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Igor', 'Pavlov', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Boris', 'Pahomov', 2);

INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Olga', 'Sokolova', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Marina', 'Belova', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Maksim', 'Fomin', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Artur', 'Morozov', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Eugenia', 'Rojkova', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Elena', 'Mironova', 2);

INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Inna', 'Ivanova', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Anna', 'Lapina', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Alisa', 'Popova', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Irina', 'Burova', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Diana', 'Sidorova', 2);
INSERT INTO users (user_name, user_lastname, role_id) VALUES ('Olga', 'Popova', 2);

INSERT INTO users_courses VALUES (8, 6);
INSERT INTO users_courses VALUES (9, 5);
INSERT INTO users_courses VALUES (10, 9);
INSERT INTO users_courses VALUES (11, 3);
INSERT INTO users_courses VALUES (12, 5);
INSERT INTO users_courses VALUES (13, 2);
INSERT INTO users_courses VALUES (14, 1);
INSERT INTO users_courses VALUES (15, 7);
INSERT INTO users_courses VALUES (16, 3);
INSERT INTO users_courses VALUES (17, 7);
INSERT INTO users_courses VALUES (18, 10);
INSERT INTO users_courses VALUES (18, 9);
INSERT INTO users_courses VALUES (19, 4);
INSERT INTO users_courses VALUES (20, 9);
INSERT INTO users_courses VALUES (21, 5);
INSERT INTO users_courses VALUES (21, 10);
INSERT INTO users_courses VALUES (22, 6);
INSERT INTO users_courses VALUES (22, 8);
INSERT INTO users_courses VALUES (23, 6);
INSERT INTO users_courses VALUES (24, 4);
INSERT INTO users_courses VALUES (25, 10);
INSERT INTO users_courses VALUES (25, 2);
INSERT INTO users_courses VALUES (26, 2);
INSERT INTO users_courses VALUES (27, 1);
INSERT INTO users_courses VALUES (26, 6);
INSERT INTO users_courses VALUES (26, 8);
INSERT INTO users_courses VALUES (29, 1);
INSERT INTO users_courses VALUES (30, 9);
INSERT INTO users_courses VALUES (31, 1);
INSERT INTO users_courses VALUES (32, 5);
INSERT INTO users_courses VALUES (33, 6);
INSERT INTO users_courses VALUES (33, 7);
INSERT INTO users_courses VALUES (34, 6);
INSERT INTO users_courses VALUES (35, 4);
INSERT INTO users_courses VALUES (36, 1);
INSERT INTO users_courses VALUES (37, 2);
INSERT INTO users_courses VALUES (37, 10);
INSERT INTO users_courses VALUES (38, 6);
INSERT INTO users_courses VALUES (39, 6);
INSERT INTO users_courses VALUES (40, 5);
INSERT INTO users_courses VALUES (41, 1);
INSERT INTO users_courses VALUES (42, 2);
INSERT INTO users_courses VALUES (42, 10);
INSERT INTO users_courses VALUES (43, 8);
INSERT INTO users_courses VALUES (43, 5);

INSERT INTO users_groups VALUES (8, 1);
INSERT INTO users_groups VALUES (9, 1);
INSERT INTO users_groups VALUES (10, 1);
INSERT INTO users_groups VALUES (11, 1);
INSERT INTO users_groups VALUES (12, 1);
INSERT INTO users_groups VALUES (13, 1);
INSERT INTO users_groups VALUES (14, 2);
INSERT INTO users_groups VALUES (15, 2);
INSERT INTO users_groups VALUES (16, 2);
INSERT INTO users_groups VALUES (17, 2);
INSERT INTO users_groups VALUES (18, 2);
INSERT INTO users_groups VALUES (19, 2);
INSERT INTO users_groups VALUES (20, 3);
INSERT INTO users_groups VALUES (21, 3);
INSERT INTO users_groups VALUES (22, 3);
INSERT INTO users_groups VALUES (23, 3);
INSERT INTO users_groups VALUES (24, 3);
INSERT INTO users_groups VALUES (25, 3);
INSERT INTO users_groups VALUES (26, 4);
INSERT INTO users_groups VALUES (27, 4);
INSERT INTO users_groups VALUES (28, 4);
INSERT INTO users_groups VALUES (29, 4);
INSERT INTO users_groups VALUES (30, 4);
INSERT INTO users_groups VALUES (31, 4);
INSERT INTO users_groups VALUES (32, 5);
INSERT INTO users_groups VALUES (33, 5);
INSERT INTO users_groups VALUES (34, 5);
INSERT INTO users_groups VALUES (35, 5);
INSERT INTO users_groups VALUES (36, 5);
INSERT INTO users_groups VALUES (37, 5);
INSERT INTO users_groups VALUES (38, 6);
INSERT INTO users_groups VALUES (39, 6);
INSERT INTO users_groups VALUES (40, 6);
INSERT INTO users_groups VALUES (41, 6);
INSERT INTO users_groups VALUES (42, 6);
INSERT INTO users_groups VALUES (43, 6);